version: '3'
services:
  toko_kelontong:
    build: ./php
    image: laravel:latest
    container_name: toko_kelontong
    hostname: "toko_kelontong"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - db_toko_kelontong

  db_toko_kelontong:
    image: mariadb:10.2
    container_name: db_toko_kelontong
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./database/data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_DATABASE: your_database
      MYSQL_USER: droid
      MYSQL_PASSWORD: roid1234
      MYSQL_ROOT_PASSWORD: roid12345
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx_toko:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_toko
    hostname: "nginx_toko"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - toko_kelontong
